using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DamageTerror.Enums;

[JsonConverter(typeof(StringEnumConverter))]
public enum BarColumn
{
    Dps = 0,
    Hps = 1,
    Damage = 2,
    Healed = 3,
    DamagePercent = 4,
    HealPercent = 5,
    DirectHit = 6,
    Crit = 7,
    CritDirectHit = 8,
    Deaths = 9,
    DamageTaken = 10,
    DamageTakenPercent = 11,
    Overheal = 12,
    OverhealAmount = 13,
    MaxHit = 14,
    MaxHitValue = 15,
    PeakDps = 16,
    MaxHeal = 17,
    MaxHealValue = 18,
    Swings = 19,
    Hits = 20,
    Misses = 21,
    HitRate = 22,
    CritHitCount = 23,
    DirectHitCount = 24,
    CritDirectHitCount = 25,
    BlockPct = 26,
    ParryPct = 27,
    HealsTaken = 28,
    AbsorbHeal = 29,
    Kills = 30,
    InstantDps = 31,
    InstantHps = 32,
    CritHealPct = 33,
    HealCount = 34,
    CombatantDuration = 35,
    DamageShield = 36,
    MaxHealWard = 37,
    PowerDrain = 38,
    PowerHeal = 39,
    LegsSweeped = 40,
    SkillIssue = 41,
    DamageDown = 42,
    Positionals = 43,
    PositionalHits = 44,
    PositionalMisses = 45,
    EncDps = 46,
    EncHps = 47,
    DpsRank = 48,
    HpsRank = 49,

    // Group totals (sum of filtered combatants)
    GroupDps = 50,
    GroupHps = 51,
    GroupDamage = 52,
    GroupHealed = 53,
    GroupDamageTaken = 54,
    GroupDeaths = 55,
    GroupOverheal = 56,
    GroupInstantDps = 57,
    GroupInstantHps = 58,
    GroupSkillIssue = 59,
    GroupDamageDown = 60,

    // Group averages (mean of filtered combatants)
    GroupAvgDps = 61,
    GroupAvgHps = 62,
    GroupAvgCrit = 63,
    GroupAvgDirectHit = 64,
    GroupAvgCritDirectHit = 65,
    GroupAvgOverhealPct = 66,
    GroupAvgCritHealPct = 67,
    GroupAvgHitRate = 68,

    // Group max (best in filtered combatants)
    GroupPeakDps = 69,
    GroupMaxHitValue = 70,
    GroupMaxHealValue = 71,
}
