namespace DamageTerror.Enums;

public enum BarColumn
{
    Dps,
    Hps,
    Damage,
    Healed,
    DamagePercent,
    HealPercent,
    DirectHit,
    Crit,
    CritDirectHit,
    Deaths,
    DamageTaken,
    DamageTakenPercent,
    Overheal,
    OverhealAmount,
    MaxHit,
    MaxHitValue,
    PeakDps,
    MaxHeal,
    MaxHealValue,
    Swings,
    Hits,
    Misses,
    HitRate,
    CritHitCount,
    DirectHitCount,
    CritDirectHitCount,
    BlockPct,
    ParryPct,
    HealsTaken,
    AbsorbHeal,
    Kills,
    InstantDps,
    InstantHps,
    CritHealPct,
    HealCount,
    CombatantDuration,
    DamageShield,
    MaxHealWard,
    PowerDrain,
    PowerHeal,
    LegsSweeped,
    SkillIssue,
    EncDps,
    EncHps,
    DpsRank,
    HpsRank,

    // Group totals (sum of filtered combatants)
    GroupDps,
    GroupHps,
    GroupDamage,
    GroupHealed,
    GroupDamageTaken,
    GroupDeaths,
    GroupOverheal,
    GroupInstantDps,
    GroupInstantHps,

    // Group averages (mean of filtered combatants)
    GroupAvgDps,
    GroupAvgHps,
    GroupAvgCrit,
    GroupAvgDirectHit,
    GroupAvgCritDirectHit,
    GroupAvgOverhealPct,
    GroupAvgCritHealPct,
    GroupAvgHitRate,

    // Group max (best in filtered combatants)
    GroupPeakDps,
    GroupMaxHitValue,
    GroupMaxHealValue,
}
