using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DamageTerror.Enums;

[JsonConverter(typeof(StringEnumConverter))]
public enum BarColumn
{
    Dps = 0,
    Hps = 1,
    Damage = 2,
    Healed = 3,
    DamagePercent = 4,
    HealPercent = 5,
    DirectHit = 6,
    Crit = 7,
    CritDirectHit = 8,
    Deaths = 9,
    DamageTaken = 10,
    DamageTakenPercent = 11,
    Overheal = 12,
    OverhealAmount = 13,
    MaxHit = 14,
    MaxHitValue = 15,
    PeakDps = 16,
    MaxHeal = 17,
    MaxHealValue = 18,
    Swings = 19,
    Hits = 20,
    Misses = 21,
    HitRate = 22,
    CritHitCount = 23,
    DirectHitCount = 24,
    CritDirectHitCount = 25,
    BlockPct = 26,
    ParryPct = 27,
    HealsTaken = 28,
    AbsorbHeal = 29,
    Kills = 30,
    InstantDps = 31,
    InstantHps = 32,
    CritHealPct = 33,
    HealCount = 34,
    CombatantDuration = 35,
    DamageShield = 36,
    MaxHealWard = 37,
    PowerDrain = 38,
    PowerHeal = 39,
    LegsSweeped = 40,
    SkillIssue = 41,
    DamageDown = 42,
    Positionals = 43,
    PositionalHits = 44,
    PositionalMisses = 45,
    PositionalPct = 46,
    EncDps = 47,
    EncHps = 48,
    DpsRank = 49,
    HpsRank = 50,

    GroupDps = 51,
    GroupHps = 52,
    GroupDamage = 53,
    GroupHealed = 54,
    GroupDamageTaken = 55,
    GroupDeaths = 56,
    GroupOverheal = 57,
    GroupInstantDps = 58,
    GroupInstantHps = 59,
    GroupSkillIssue = 60,
    GroupDamageDown = 61,

    GroupAvgDps = 62,
    GroupAvgHps = 63,
    GroupAvgCrit = 64,
    GroupAvgDirectHit = 65,
    GroupAvgCritDirectHit = 66,
    GroupAvgOverhealPct = 67,
    GroupAvgCritHealPct = 68,
    GroupAvgHitRate = 69,

    GroupPeakDps = 70,
    GroupMaxHitValue = 71,
    GroupMaxHealValue = 72,
}
