using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace DamageTerror.Enums;

[JsonConverter(typeof(StringEnumConverter))]
public enum TooltipField
{
    Name = 0,
    Job = 1,
    Dps = 2,
    Hps = 3,
    Damage = 4,
    Healed = 5,
    DamagePercent = 6,
    HealPercent = 7,
    Crit = 8,
    DirectHit = 9,
    CritDirectHit = 10,
    Deaths = 11,
    DamageTaken = 12,
    Overheal = 13,
    OverhealAmount = 14,
    MaxHit = 15,
    MaxHitValue = 16,
    MaxHeal = 17,
    MaxHealValue = 18,
    PeakDps = 19,
    Swings = 20,
    Hits = 21,
    Misses = 22,
    HitRate = 23,
    Kills = 24,
    CombatantDuration = 25,
    HealsTaken = 26,
    InstantDps = 27,
    InstantHps = 28,
    CritHealPct = 29,
    HealCount = 30,
    DamageShield = 31,
    MaxHealWard = 32,
    LegsSweeped = 33,
    SkillIssue = 34,
    DamageDown = 35,
    Positionals = 36,
    PositionalHits = 37,
    PositionalMisses = 38,
    EncDps = 39,
    EncHps = 40,
    TopDamageSkills = 41,
    TopHealingSkills = 42,
}
