namespace DamageTerror.Helpers;

public static class ColumnLabels
{
    public static readonly Dictionary<BarColumn, string> DefaultHeaderLabels = new()
    {
        { BarColumn.Dps, "DPS" },
        { BarColumn.Hps, "HPS" },
        { BarColumn.Damage, "Dmg" },
        { BarColumn.Healed, "Heal" },
        { BarColumn.DamagePercent, "D%" },
        { BarColumn.HealPercent, "H%" },
        { BarColumn.DirectHit, "!" },
        { BarColumn.Crit, "!!" },
        { BarColumn.CritDirectHit, "!!!" },
        { BarColumn.Deaths, "D" },
        { BarColumn.DamageTaken, "Taken" },
        { BarColumn.DamageTakenPercent, "T%" },
        { BarColumn.Overheal, "OH%" },
        { BarColumn.OverhealAmount, "OH" },
        { BarColumn.MaxHit, "Max" },
        { BarColumn.MaxHitValue, "MaxV" },
        { BarColumn.PeakDps, "Peak" },
        { BarColumn.MaxHeal, "MH" },
        { BarColumn.MaxHealValue, "MHV" },
        { BarColumn.Swings, "Sw" },
        { BarColumn.Hits, "Hits" },
        { BarColumn.Misses, "Miss" },
        { BarColumn.HitRate, "Acc" },
        { BarColumn.CritHitCount, "C#" },
        { BarColumn.DirectHitCount, "D#" },
        { BarColumn.CritDirectHitCount, "CD#" },
        { BarColumn.BlockPct, "Blk" },
        { BarColumn.ParryPct, "Par" },
        { BarColumn.HealsTaken, "HT" },
        { BarColumn.AbsorbHeal, "Abs" },
        { BarColumn.Kills, "K" },
        { BarColumn.InstantDps, "iDPS" },
        { BarColumn.InstantHps, "iHPS" },
        { BarColumn.CritHealPct, "CH%" },
        { BarColumn.HealCount, "HC" },
        { BarColumn.CombatantDuration, "Dur" },
        { BarColumn.DamageShield, "Shld" },
        { BarColumn.MaxHealWard, "MHW" },
        { BarColumn.PowerDrain, "MPD" },
        { BarColumn.PowerHeal, "MPR" },
        { BarColumn.LegsSweeped, "LS" },
        { BarColumn.SkillIssue, "SI" },
        { BarColumn.DamageDown, "DD" },
        { BarColumn.Positionals, "Pos" },
        { BarColumn.PositionalHits, "PosH" },
        { BarColumn.PositionalMisses, "PosM" },
        { BarColumn.PositionalPct, "Pos%" },
        { BarColumn.EncDps, "eDPS" },
        { BarColumn.EncHps, "eHPS" },
        { BarColumn.DpsRank, "Rank" },
        { BarColumn.HpsRank, "Rank" },
        { BarColumn.GroupDps, "gΣDPS" },
        { BarColumn.GroupHps, "gΣHPS" },
        { BarColumn.GroupDamage, "gΣDmg" },
        { BarColumn.GroupHealed, "gΣHeal" },
        { BarColumn.GroupDamageTaken, "gΣTkn" },
        { BarColumn.GroupDeaths, "gΣD" },
        { BarColumn.GroupOverheal, "gΣOH" },
        { BarColumn.GroupSkillIssue, "gΣSI" },
        { BarColumn.GroupDamageDown, "gΣDD" },
        { BarColumn.GroupInstantDps, "gΣiDPS" },
        { BarColumn.GroupInstantHps, "gΣiHPS" },
        { BarColumn.GroupAvgDps, "gx̄DPS" },
        { BarColumn.GroupAvgHps, "gx̄HPS" },
        { BarColumn.GroupAvgCrit, "gx̄!!" },
        { BarColumn.GroupAvgDirectHit, "gx̄!" },
        { BarColumn.GroupAvgCritDirectHit, "gx̄!!!" },
        { BarColumn.GroupAvgOverhealPct, "gx̄OH%" },
        { BarColumn.GroupAvgCritHealPct, "gx̄CH%" },
        { BarColumn.GroupAvgHitRate, "gx̄Acc" },
        { BarColumn.GroupPeakDps, "gPeak" },
        { BarColumn.GroupMaxHitValue, "gMaxV" },
        { BarColumn.GroupMaxHealValue, "gMHV" },
    };

    public static readonly Dictionary<TooltipField, string> DefaultTooltipFieldLabels = new()
    {
        { TooltipField.Name, "Name" },
        { TooltipField.Job, "Job" },
        { TooltipField.Dps, "DPS" },
        { TooltipField.Hps, "HPS" },
        { TooltipField.Damage, "Damage" },
        { TooltipField.Healed, "Healed" },
        { TooltipField.DamagePercent, "Damage %" },
        { TooltipField.HealPercent, "Heal %" },
        { TooltipField.Crit, "Crit %" },
        { TooltipField.DirectHit, "Direct Hit %" },
        { TooltipField.CritDirectHit, "Crit DH %" },
        { TooltipField.Deaths, "Deaths" },
        { TooltipField.DamageTaken, "Damage Taken" },
        { TooltipField.Overheal, "Overheal %" },
        { TooltipField.OverhealAmount, "Overheal" },
        { TooltipField.MaxHit, "Max Hit" },
        { TooltipField.MaxHitValue, "Max Hit Value" },
        { TooltipField.MaxHeal, "Max Heal" },
        { TooltipField.MaxHealValue, "Max Heal Value" },
        { TooltipField.PeakDps, "Peak DPS" },
        { TooltipField.Swings, "Swings" },
        { TooltipField.Hits, "Hits" },
        { TooltipField.Misses, "Misses" },
        { TooltipField.HitRate, "Hit Rate" },
        { TooltipField.Kills, "Kills" },
        { TooltipField.CombatantDuration, "Duration" },
        { TooltipField.HealsTaken, "Heals Taken" },
        { TooltipField.InstantDps, "Instant DPS" },
        { TooltipField.InstantHps, "Instant HPS" },
        { TooltipField.CritHealPct, "Crit Heal %" },
        { TooltipField.HealCount, "Heal Count" },
        { TooltipField.DamageShield, "Damage Shield" },
        { TooltipField.MaxHealWard, "Max Heal Ward" },
        { TooltipField.LegsSweeped, "Legs Sweeped" },
        { TooltipField.SkillIssue, "Skill Issue" },
        { TooltipField.DamageDown, "Damage Down" },
        { TooltipField.Positionals, "Positionals" },
        { TooltipField.PositionalHits, "Positional Hits" },
        { TooltipField.PositionalMisses, "Positional Misses" },
        { TooltipField.PositionalPct, "Positional %" },
        { TooltipField.EncDps, "Encounter DPS" },
        { TooltipField.EncHps, "Encounter HPS" },
        { TooltipField.TopDamageSkills, "Top Damage Skills" },
        { TooltipField.TopHealingSkills, "Top Healing Skills" },
    };

    public static readonly Dictionary<BarColumn, string> DefaultDetailColumnLabels = new()
    {
        { BarColumn.Dps, "DPS" },
        { BarColumn.InstantDps, "iDPS" },
        { BarColumn.PeakDps, "Peak" },
        { BarColumn.Damage, "Total" },
        { BarColumn.DamagePercent, "Dmg %" },
        { BarColumn.MaxHit, "Max Hit" },
        { BarColumn.MaxHitValue, "Max Hit Value" },
        { BarColumn.DamageShield, "Shield" },
        { BarColumn.EncDps, "Encounter DPS" },
        { BarColumn.Hps, "HPS" },
        { BarColumn.InstantHps, "iHPS" },
        { BarColumn.Healed, "Total" },
        { BarColumn.HealPercent, "Heal %" },
        { BarColumn.Overheal, "Overheal" },
        { BarColumn.OverhealAmount, "OH Amt" },
        { BarColumn.CritHealPct, "Crit Heal" },
        { BarColumn.MaxHeal, "Max Heal" },
        { BarColumn.MaxHealValue, "Max Heal Value" },
        { BarColumn.HealCount, "Heals" },
        { BarColumn.EncHps, "Encounter HPS" },
        { BarColumn.Crit, "Crit" },
        { BarColumn.DirectHit, "DH" },
        { BarColumn.CritDirectHit, "CDH" },
        { BarColumn.CritHitCount, "Crit#" },
        { BarColumn.DirectHitCount, "DH#" },
        { BarColumn.CritDirectHitCount, "CDH#" },
        { BarColumn.HitRate, "Hit Rate" },
        { BarColumn.Swings, "Swings" },
        { BarColumn.Hits, "Hits" },
        { BarColumn.Misses, "Misses" },
        { BarColumn.DamageTaken, "Taken" },
        { BarColumn.DamageTakenPercent, "Taken %" },
        { BarColumn.BlockPct, "Block" },
        { BarColumn.ParryPct, "Parry" },
        { BarColumn.HealsTaken, "Heals Taken" },
        { BarColumn.Deaths, "Deaths" },
        { BarColumn.Kills, "Kills" },
        { BarColumn.CombatantDuration, "Duration" },
        { BarColumn.PowerHeal, "MP Recovery" },
        { BarColumn.PowerDrain, "MP Drain" },
        { BarColumn.AbsorbHeal, "Absorb" },
        { BarColumn.MaxHealWard, "Max Ward" },
        { BarColumn.LegsSweeped, "LS" },
        { BarColumn.SkillIssue, "Skill Issue" },
        { BarColumn.DamageDown, "Damage Down" },
        { BarColumn.Positionals, "Positionals" },
        { BarColumn.PositionalHits, "Positional Hits" },
        { BarColumn.PositionalMisses, "Positional Misses" },
        { BarColumn.PositionalPct, "Positional %" },
    };

    public static readonly Dictionary<BarColumn, string> FullColumnNames = new()
    {
        { BarColumn.Dps, "Damage Per Second" },
        { BarColumn.Hps, "Healing Per Second" },
        { BarColumn.Damage, "Total Damage" },
        { BarColumn.Healed, "Total Healed" },
        { BarColumn.DamagePercent, "Damage %" },
        { BarColumn.HealPercent, "Healing %" },
        { BarColumn.DirectHit, "Direct Hit %" },
        { BarColumn.Crit, "Critical Hit %" },
        { BarColumn.CritDirectHit, "Critical Direct Hit %" },
        { BarColumn.Deaths, "Deaths" },
        { BarColumn.DamageTaken, "Damage Taken" },
        { BarColumn.DamageTakenPercent, "Damage Taken %" },
        { BarColumn.Overheal, "Overheal %" },
        { BarColumn.OverhealAmount, "Overheal Amount" },
        { BarColumn.MaxHit, "Max Hit" },
        { BarColumn.MaxHitValue, "Max Hit Value" },
        { BarColumn.PeakDps, "Peak DPS" },
        { BarColumn.MaxHeal, "Max Heal" },
        { BarColumn.MaxHealValue, "Max Heal Value" },
        { BarColumn.Swings, "Swings" },
        { BarColumn.Hits, "Hits" },
        { BarColumn.Misses, "Misses" },
        { BarColumn.HitRate, "Hit Rate / Accuracy" },
        { BarColumn.CritHitCount, "Critical Hit Count" },
        { BarColumn.DirectHitCount, "Direct Hit Count" },
        { BarColumn.CritDirectHitCount, "Critical Direct Hit Count" },
        { BarColumn.BlockPct, "Block %" },
        { BarColumn.ParryPct, "Parry %" },
        { BarColumn.HealsTaken, "Heals Taken" },
        { BarColumn.AbsorbHeal, "Absorb / Shield Heal" },
        { BarColumn.Kills, "Kills" },
        { BarColumn.InstantDps, "Instant DPS" },
        { BarColumn.InstantHps, "Instant HPS" },
        { BarColumn.CritHealPct, "Critical Heal %" },
        { BarColumn.HealCount, "Heal Count" },
        { BarColumn.CombatantDuration, "Combatant Duration" },
        { BarColumn.DamageShield, "Damage Shield" },
        { BarColumn.MaxHealWard, "Max Heal Ward" },
        { BarColumn.PowerDrain, "MP Drain" },
        { BarColumn.PowerHeal, "MP Restore" },
        { BarColumn.LegsSweeped, "Legs Sweeped" },
        { BarColumn.SkillIssue, "Skill Issue" },
        { BarColumn.DamageDown, "Damage Down" },
        { BarColumn.Positionals, "Positionals" },
        { BarColumn.PositionalHits, "Positional Hits" },
        { BarColumn.PositionalMisses, "Positional Misses" },
        { BarColumn.PositionalPct, "Positional %" },
        { BarColumn.EncDps, "Encounter DPS" },
        { BarColumn.EncHps, "Encounter HPS" },
        { BarColumn.DpsRank, "DPS Rank" },
        { BarColumn.HpsRank, "HPS Rank" },
    };
}
