<Project Sdk="Dalamud.NET.Sdk/14.0.1">
  <PropertyGroup>
    <AssemblyName>DamageTerror</AssemblyName>
    <Authors>MTVirux</Authors>
    <Description>Native ImGui damage meter overlay for FFXIV, powered by IINACT.</Description>
    <Version>1.1.0.7</Version>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Include="DamageTerror.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dalamud.Bindings.ImPlot">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImPlot.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OtterGui\OtterGui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommons\ECommons\ECommons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NightmareUI\NightmareUI\NightmareUI.csproj" />
    <ProjectReference Include="..\NightmareUI.OtterGuiWrapper\NightmareUI.OtterGuiWrapper\NightmareUI.OtterGuiWrapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.0-preview.3.25173.2" />
  </ItemGroup>
</Project>
